sonar.projectKey=RobelManoa_Moustass_project
sonar.projectName=Moustass Backend
sonar.organization=robelmanoa
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.d.ts
sonar.typescript.tsconfigPath=tsconfig.json