sonar.projectKey=RobelManoa_Moustass_project
sonar.projectName=Moustass Backend
sonar.organization=robelmanoa
sonar.sources=src
sonar.tests=src/**/*.test.ts,src/**/*.spec.ts
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.d.ts
sonar.typescript.tsconfigPath=tsconfig.jsonsonar.coverageReportPaths=coverage/cobertura-coverage.xml
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.language=ts
sonar.testExecutionReportPaths=coverage/jest.junit.xml
